services:
  db:
    image: postgres:15
    container_name: cookbook_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cookbook
    ports:
      - "5433:5432" # Expose PostgreSQL on port 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: